-- MySQL Script generated by MySQL Workbench
-- Mon Sep  7 01:02:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema soft1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `soft1` ;

-- -----------------------------------------------------
-- Schema soft1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soft1` DEFAULT CHARACTER SET utf8 ;
USE `soft1` ;

-- -----------------------------------------------------
-- Table `soft1`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`administrador` (
  `estado` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`rol` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  `descripcion` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`usuario` (
  `id` INT(11) NOT NULL,
  `tipo_Documento_id` INT(11) NOT NULL,
  `rol_id` INT(11) NOT NULL,
  `nombre1` VARCHAR(20) NOT NULL,
  `nombre2` VARCHAR(20) NULL DEFAULT NULL,
  `apellido1` VARCHAR(20) NOT NULL,
  `apellido2` VARCHAR(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `correo` VARCHAR(70) NOT NULL,
  `contraseña` VARCHAR(25) NOT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `soft1`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_usuario_rol1_idx` ON `soft1`.`usuario` (`rol_id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`asesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`asesor` (
  `estado` INT(11) NOT NULL,
  `id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_asesor_usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `soft1`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_asesor_usuario1_idx` ON `soft1`.`asesor` (`id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`cliente` (
  `estado` INT(11) NOT NULL,
  `id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `soft1`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`pedido` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cliente_id` INT(11) NOT NULL,
  `fecha` DATETIME(6) NOT NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `fecha_Entrega` DATETIME(6) NOT NULL,
  `telefono` INT(11) NOT NULL,
  `descripcion_Pedido` VARCHAR(70) NULL DEFAULT NULL,
  `cantidad` INT(11) NOT NULL,
  `valor_Unitario` DOUBLE NOT NULL,
  `valor_iva` DOUBLE NOT NULL,
  `valor_Total` DOUBLE NOT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `soft1`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_pedido_cliente1_idx` ON `soft1`.`pedido` (`cliente_id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`tipo_pago` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_Tipo_Pago` VARCHAR(45) NOT NULL,
  `descripcion_Tipo_Pago` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`factura` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pedido_id` INT(11) NOT NULL,
  `tipo_Pago_id` INT(11) NOT NULL,
  `fecha` DATETIME(6) NOT NULL,
  `valor_Iva` DOUBLE NOT NULL,
  `valor_Total` DOUBLE NULL DEFAULT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_factura_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `soft1`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_tipo_Pago1`
    FOREIGN KEY (`tipo_Pago_id`)
    REFERENCES `soft1`.`tipo_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_factura_pedido1_idx` ON `soft1`.`factura` (`pedido_id` ASC);

CREATE INDEX `fk_factura_tipo_Pago1_idx` ON `soft1`.`factura` (`tipo_Pago_id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`logistica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`logistica` (
  `estado` INT(11) NOT NULL,
  `id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_logistica_usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `soft1`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`despacho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`despacho` (
  `id` INT(11) NOT NULL,
  `factura_id` INT(11) NOT NULL,
  `cliente_id` INT(11) NOT NULL,
  `logistica_id` INT(11) NOT NULL,
  `fecha` DATETIME(6) NOT NULL,
  `direccion_Cliente` VARCHAR(60) NOT NULL,
  `telefono` INT(11) NOT NULL,
  `nombre_Cliente` VARCHAR(80) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `descripcion_Despacho` VARCHAR(125) NOT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_despacho_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `soft1`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_despacho_factura1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `soft1`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_despacho_logistica1`
    FOREIGN KEY (`logistica_id`)
    REFERENCES `soft1`.`logistica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_despacho_factura1_idx` ON `soft1`.`despacho` (`factura_id` ASC);

CREATE INDEX `fk_despacho_logistica1_idx` ON `soft1`.`despacho` (`logistica_id` ASC);

CREATE INDEX `fk_despacho_cliente1_idx` ON `soft1`.`despacho` (`cliente_id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`tipo_repuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`tipo_repuesto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_Tipo_Repuesto` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`repuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`repuesto` (
  `id` INT(11) NOT NULL,
  `tipo_Repuesto_id` INT(11) NOT NULL,
  `fecha_Registro_Repuesto` DATETIME NOT NULL,
  `nombre_Repuesto` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `imagen` LONGBLOB NOT NULL,
  `descripcion_repuesto` VARCHAR(60) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `valor_Compra` DOUBLE NOT NULL,
  `valor_Venta` DOUBLE NOT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_repuesto_tipo_Repuesto1`
    FOREIGN KEY (`tipo_Repuesto_id`)
    REFERENCES `soft1`.`tipo_repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_repuesto_tipo_Repuesto1_idx` ON `soft1`.`repuesto` (`tipo_Repuesto_id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`solicitud_compra_repuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`solicitud_compra_repuestos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `logistica_id` INT(11) NOT NULL,
  `repuesto_id` INT(11) NOT NULL,
  `fecha` DATETIME(6) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_solicitud_Compra_Repuestos_logistica1`
    FOREIGN KEY (`logistica_id`)
    REFERENCES `soft1`.`logistica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_Compra_Repuestos_repuesto1`
    FOREIGN KEY (`repuesto_id`)
    REFERENCES `soft1`.`repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_solicitud_Compra_Repuestos_repuesto1_idx` ON `soft1`.`solicitud_compra_repuestos` (`repuesto_id` ASC);

CREATE INDEX `fk_solicitud_Compra_Repuestos_logistica1_idx` ON `soft1`.`solicitud_compra_repuestos` (`logistica_id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`vendedor` (
  `estado` INT(11) NOT NULL,
  `id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_vendedor_usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `soft1`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`orden_compra_repuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`orden_compra_repuesto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `solicitud_Compra_Repuestos_id` INT(11) NOT NULL,
  `vendedor_id` INT(11) NOT NULL,
  `fecha` DATETIME(6) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `valor_unitario` DOUBLE NOT NULL,
  `valor_Iva` DOUBLE NOT NULL,
  `valor_Total` DOUBLE NOT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_orden_Compra_Repuesto_solicitud_Compra_Repuestos1`
    FOREIGN KEY (`solicitud_Compra_Repuestos_id`)
    REFERENCES `soft1`.`solicitud_compra_repuestos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_Compra_Repuesto_vendedor1`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `soft1`.`vendedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_orden_Compra_Repuesto_solicitud_Compra_Repuestos1_idx` ON `soft1`.`orden_compra_repuesto` (`solicitud_Compra_Repuestos_id` ASC);

CREATE INDEX `fk_orden_Compra_Repuesto_vendedor1_idx` ON `soft1`.`orden_compra_repuesto` (`vendedor_id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`orden_compra_repuesto_has_repuesto1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`orden_compra_repuesto_has_repuesto1` (
  `orden_Compra_Repuesto_id` INT(11) NOT NULL,
  `repuesto_id` INT(11) NOT NULL,
  PRIMARY KEY (`orden_Compra_Repuesto_id`, `repuesto_id`),
  CONSTRAINT `fk_orden_Compra_Repuesto_has_repuesto1_orden_Compra_Repuesto1`
    FOREIGN KEY (`orden_Compra_Repuesto_id`)
    REFERENCES `soft1`.`orden_compra_repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_Compra_Repuesto_has_repuesto1_repuesto1`
    FOREIGN KEY (`repuesto_id`)
    REFERENCES `soft1`.`repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_orden_Compra_Repuesto_has_repuesto1_repuesto1_idx` ON `soft1`.`orden_compra_repuesto_has_repuesto1` (`repuesto_id` ASC);

CREATE INDEX `fk_orden_Compra_Repuesto_has_repuesto1_orden_Compra_Repuest_idx` ON `soft1`.`orden_compra_repuesto_has_repuesto1` (`orden_Compra_Repuesto_id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`pqrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`pqrs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cliente_id` INT(11) NOT NULL,
  `asesor_id` INT(11) NOT NULL,
  `fecha` DATETIME(6) NOT NULL,
  `descripcion` VARCHAR(120) NOT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_PQRS_asesor1`
    FOREIGN KEY (`asesor_id`)
    REFERENCES `soft1`.`asesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PQRS_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `soft1`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_PQRS_cliente1_idx` ON `soft1`.`pqrs` (`cliente_id` ASC);

CREATE INDEX `fk_PQRS_asesor1_idx` ON `soft1`.`pqrs` (`asesor_id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`tipo_pqrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`tipo_pqrs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_PQRS` VARCHAR(25) NOT NULL,
  `descripcion_PQRS` VARCHAR(60) NOT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`pqrs_has_tipo_pqrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`pqrs_has_tipo_pqrs` (
  `PQRS_id` INT(11) NOT NULL,
  `tipo_PQRS_id` INT(11) NOT NULL,
  PRIMARY KEY (`PQRS_id`, `tipo_PQRS_id`),
  CONSTRAINT `fk_PQRS_has_tipo_PQRS_PQRS1`
    FOREIGN KEY (`PQRS_id`)
    REFERENCES `soft1`.`pqrs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PQRS_has_tipo_PQRS_tipo_PQRS1`
    FOREIGN KEY (`tipo_PQRS_id`)
    REFERENCES `soft1`.`tipo_pqrs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_PQRS_has_tipo_PQRS_tipo_PQRS1_idx` ON `soft1`.`pqrs_has_tipo_pqrs` (`tipo_PQRS_id` ASC);

CREATE INDEX `fk_PQRS_has_tipo_PQRS_PQRS1_idx` ON `soft1`.`pqrs_has_tipo_pqrs` (`PQRS_id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`proveedor` (
  `id` INT(11) NOT NULL,
  `nombre_Proveedor` VARCHAR(60) NOT NULL,
  `direccion_Proveedor` VARCHAR(60) NOT NULL,
  `telefono_Proveedor` INT(11) NOT NULL,
  `correo_Proveedor` VARCHAR(70) NULL DEFAULT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`repuesto_has_despacho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`repuesto_has_despacho` (
  `repuesto_id` INT(11) NOT NULL,
  `despacho_id` INT(11) NOT NULL,
  PRIMARY KEY (`repuesto_id`, `despacho_id`),
  CONSTRAINT `fk_repuesto_has_despacho_despacho1`
    FOREIGN KEY (`despacho_id`)
    REFERENCES `soft1`.`despacho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repuesto_has_despacho_repuesto1`
    FOREIGN KEY (`repuesto_id`)
    REFERENCES `soft1`.`repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_repuesto_has_despacho_despacho1_idx` ON `soft1`.`repuesto_has_despacho` (`despacho_id` ASC);

CREATE INDEX `fk_repuesto_has_despacho_repuesto1_idx` ON `soft1`.`repuesto_has_despacho` (`repuesto_id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`repuesto_has_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`repuesto_has_factura` (
  `repuesto_id` INT(11) NOT NULL,
  `factura_id` INT(11) NOT NULL,
  PRIMARY KEY (`repuesto_id`, `factura_id`),
  CONSTRAINT `fk_repuesto_has_factura_factura1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `soft1`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repuesto_has_factura_repuesto1`
    FOREIGN KEY (`repuesto_id`)
    REFERENCES `soft1`.`repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_repuesto_has_factura_factura1_idx` ON `soft1`.`repuesto_has_factura` (`factura_id` ASC);

CREATE INDEX `fk_repuesto_has_factura_repuesto1_idx` ON `soft1`.`repuesto_has_factura` (`repuesto_id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`repuesto_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`repuesto_has_pedido` (
  `repuesto_id` INT(11) NOT NULL,
  `pedido_id` INT(11) NOT NULL,
  PRIMARY KEY (`repuesto_id`, `pedido_id`),
  CONSTRAINT `fk_repuesto_has_pedido_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `soft1`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repuesto_has_pedido_repuesto1`
    FOREIGN KEY (`repuesto_id`)
    REFERENCES `soft1`.`repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_repuesto_has_pedido_pedido1_idx` ON `soft1`.`repuesto_has_pedido` (`pedido_id` ASC);

CREATE INDEX `fk_repuesto_has_pedido_repuesto1_idx` ON `soft1`.`repuesto_has_pedido` (`repuesto_id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`repuesto_has_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`repuesto_has_proveedor` (
  `repuesto_id` INT(11) NOT NULL,
  `proveedor_id` INT(11) NOT NULL,
  PRIMARY KEY (`repuesto_id`, `proveedor_id`),
  CONSTRAINT `fk_repuesto_has_proveedor_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `soft1`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repuesto_has_proveedor_repuesto1`
    FOREIGN KEY (`repuesto_id`)
    REFERENCES `soft1`.`repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_repuesto_has_proveedor_proveedor1_idx` ON `soft1`.`repuesto_has_proveedor` (`proveedor_id` ASC);

CREATE INDEX `fk_repuesto_has_proveedor_repuesto1_idx` ON `soft1`.`repuesto_has_proveedor` (`repuesto_id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`telefono` (
  `id` INT(11) NOT NULL,
  `numero_Telefono` VARCHAR(15) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_telefono_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `soft1`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_telefono_usuario1_idx` ON `soft1`.`telefono` (`usuario_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
